spring:
  application:
    name: "dca-product-service"
    upload-enabled: false
    database-persistence: false
    licensed:
      zapier: "1111111-2222-3333-4444-5555555"

aws:
  s3:
    bucket: "invoices"
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    keys:
      access: "test"
      secret: "test"
  dynamodb:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    table: "invoice"
    keys:
      access: "test"
      secret: "test"

security:
  licensed-apps:
    - local-postman